export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCESS = 'AUTH_SUCESS';
export const AUTH_FAIL = 'AUTH_FAIL';